# ---- Base Node ----

FROM node:13-alpine AS base

RUN apk add --no-cache tini

ENV appdir /partnadem/src/bot

RUN mkdir -p ${appdir}
WORKDIR ${appdir}
COPY package*.json ${appdir}

# ---- Dependencies ----
FROM base AS dependencies
RUN npm install -g @nestjs/cli
RUN npm install 
RUN npm install --only=dev

# ---- Build ----
FROM dependencies AS build
COPY . .

# ---- Release ----
FROM build AS release
EXPOSE 3000
CMD ["tini","npm", "run", "start:dev"]